/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rafaelpaz' at '16/11/18 5:58 PM' with Gradle 2.14.1
 *
 * @author rafaelpaz, @date 16/11/18 5:58 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
